### ISSUE TITLE
Ongoing Maintenance

### ISSUE THREAD

**Issue by bentok** [alfonsogarciacaro/fable-flutterapp#2]
Hey Alfonso!

I've been using fable for my Flutter app for a while now, but I'm still only doing my redux models, and all my utility functions in F#, and am using Dart still for my widgets.

The main reason is because I still don't understand how to generate bindings for dart libraries using this (https://github.com/alfonsogarciacaro/DartToFableBindings).

I wanted to reach out to you and let you know that I would love to help maintain the core Flutter bindings, as well as the DartToFableBindings library. But I think my main problem is, I simply do not know enough about how Fable works internally to generate Dart code.

How would you recommend that I get more familiar with how all of this works? This is an amazing project and I would love to help as much as I can - specifically in the Dart area.

**Comment by johnstorey** [comment]
@bentok In a moment of serendipity, I chose today to check on the progress of this project. I just started an F# job and last looked at this early in the year, but would love to chip in where I can. Let me know if you're looking for a collaborator.

**Comment by bentok** [comment]
@johnstorey Heck yeah! I've done a few attempts at generating bindings to varying degrees of success, but I am just too ignorant of what the F# classes need to look like for Dart bindings.

Here is the project I think Alfonso used to generate the Flutter bindings: https://github.com/alfonsogarciacaro/DartToFableBindings

I'd like to help make that library ready to generate bindings for Dart libraries like Dio. I imagine it would be a similar process between the core Flutter library and 3rd party libraries.

I would 100% love to be a collaborator on this with you.

**Comment by johnstorey** [comment]
Will look at the project. I seem to recall an article from you about having the first app with this code in the app store. On my side I'm starting with this whole ecosystem, so it makes sense for me to follow your lead here. I'll get started studying this and trying to figure it out today.

**Comment by johnstorey** [comment]
@bentok Not sure the best way to communicate with you outside of the issue queue. But I have sat down, got this repo and sample app running, and am getting a grip on the code. Would love to chat about how to prioritize and split up the work.

**Comment by bentok** [comment]
@johnstorey  Sweet! I'm on the F# Foundation Slack (Ben Copeland), on the F# Discord community (Bentok), and I'm on Mastadon (@bentok@mastodon.gamedev.place). I'd love to connect with you if you are on any of those.
